#!/bin/bash
surfaceFeatureExtract #surfaceFeatures for OpenFOAM7
blockMesh
decomposePar
mpiexec -np 48 snappyHexMesh -parallel -overwrite
mpiexec -np 48 checkMesh -parallel -latestTime 
reconstructParMesh -mergeTol 1e-06 -constant
